### ISSUE TITLE
wishlist item: true alpha-channel transparency

### ISSUE THREAD

**Issue by tidux** [arakiken/mlterm#2]
This is literally the only feature that MLTerm misses that I want from another terminal.

**Comment by arakiken** [comment]
Hi,

mlterm supports true transparency.

Please specify both --depth=32 and --alpha option.
--bg=rgba:rr/gg/bb/aa option also works instead of --alpha.

Take care not to specify --transbg option which enables pseudo transparency.

Regards,

mlterm and mlterm-wl on Gnome 3.34.4
http://mlterm.sf.net/mlterm-truetp.png

**Comment by tidux** [comment]
What's the way to do this through the UI?  Documentation for that would be helpful.

**Comment by tidux** [comment]
Attempted to do through the UI, alpha wouldn't stick and depth setting was missing.  Changing issue title.
