### ISSUE TITLE
Some emojis should display as wide when in sequence with Variation Selector-16 (VS-16, U+FE0F)

### ISSUE THREAD

**Issue by jquast** [arakiken/mlterm#84]
Hello,

I have authored an automatic compliance testing tool for terminals, [ucs-detect](https://ucs-detect.readthedocs.io/index.html), and I have [published results](https://ucs-detect.readthedocs.io/results.html) of mlterm and other terminals. In the results you can see that mlterm is reported as no support for Variation Selector-16 (VS-16, U+FE0F). Manual testing also shows it does not support the less common Selector-15 (U+FE0E).

![image](https://github.com/arakiken/mlterm/assets/972584/fd5102b7-f083-4000-bd43-c52b441a9cd4)

As I have [written in an article](https://www.jeffquast.com/post/ucs-detect-test-results/) about this work,

> I suspect it is some kind of "fixup" or compatibility sequence for the earliest emojis. These emojis may be displayed in either "text" or "emoji" style, and default to "text" style. In "text" style, emojis should appear without color in a single cell (Narrow), while in "emoji" style, they should display in color and occupy two cells (Wide).

The [foot](https://codeberg.org/dnkl/foot) terminal has correct support for VS-15 and VS-16:

![image](https://github.com/arakiken/mlterm/assets/972584/8f00fccf-0014-4319-b073-b52f5ee711d7)

I hope this issue and the [ucs-detect](https://ucs-detect.readthedocs.io/intro.html#ucs-detect) is helpful to your work, best wishes!

**Comment by arakiken** [comment]
Thanks for your report.
mlterm now supports VS-15 and VS-16 to some extent.
https://github.com/arakiken/mlterm/commit/2d864e6f76699647b88ffa9c8b2aa8d0a8109011

However, first of all, it is necessary to place emoji png files (https://github.com/twitter/twemoji/archive/master.zip) in ~/.mlterm/emoji or add "emoij_path = /usr/share/fonts/noto/NotoColorEmoji.ttf" to ~/.mlterm/main in order to enable color emoji glyphs in mlterm.

**Comment by jquast** [comment]
Thank you!!
